package com.personal.fatpet.service;

import com.personal.fatpet.entity.FatPetUserConfig;
import com.personal.fatpet.entity.UserDetailsConfig;
import com.personal.fatpet.model.FatPetResponse;
import com.personal.fatpet.model.UserPetDetailsModel;

import java.util.List;

public interface NodeMcuService {

  /**
   * This method will save the initialDetails for the User and fetch the autoGenerated UserId
   * @param userName
   * @param ipAddress
   * @return
   */
  FatPetResponse<UserDetailsConfig> saveInitialDetailsAndGetUserId(String userName,
      String ipAddress, String ssid);

  /**
   * This method will save the Pet Details of User
   * @param userId
   * @param userPetDetailsModel
   * @return
   */
  FatPetResponse<Boolean> savePetDetails(String userId, UserPetDetailsModel userPetDetailsModel);

  /**
   * This method will return recommended setting for a specific user
   * @param userId
   * @return
   */
  FatPetResponse<List<FatPetUserConfig>> getRecommendedSettings(String userId);
}
